apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-fridends-anonymous
  labels:
    halo.run/role-template: "true"
    halo.run/hidden: "true"
    rbac.authorization.halo.run/aggregate-to-anonymous: "true"
  annotations:
    rbac.authorization.halo.run/module: "朋友圈"
    rbac.authorization.halo.run/display-name: "朋友圈匿名接口"
rules:
  - apiGroups: ["api.friend.moony.la"]
    resources: ["parsingrss","friendposts"]
    verbs: [ "get", "list" ]

---

apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-friends-view
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/module: "朋友圈"
    rbac.authorization.halo.run/display-name: "朋友圈查看"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:friends:view"]
rules:
  - apiGroups: [ "friend.moony.la" ]
    resources: [ "friendposts","cronfriendposts" ]
    verbs: [ "get", "list" ]
  - apiGroups: [ "api.friend.moony.la" ]
    resources: [ "friendposts","parsingrss"]
    verbs: [ "get", "list" ]

---

apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-friends-manage
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/module: "朋友圈"
    rbac.authorization.halo.run/display-name: "朋友圈管理"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:friends:manage"]
    rbac.authorization.halo.run/dependencies: |
      ["role-template-friends-view"]
rules:
  - apiGroups: [ "friend.moony.la" ]
    resources: [ "friendposts","cronfriendposts"]
    verbs: [ "create", "patch", "update", "delete", "deletecollection" ]
  - apiGroups: [ "api.friend.moony.la" ]
    resources: [ "friendposts","syncrssfeed","friendposts/delete"]
    verbs: [ "create", "patch", "update", "delete", "deletecollection" ]